### ISSUE TITLE
Создание формы блога проекта

### ISSUE THREAD

**Issue by GitPushMe** [GitPushMe/IP_calculate#6]
1. Верстка формы вывода тем Блога и стилизирование.
2. Верстка формы вывода описания текущей темы Блога, её комментариев и прочей информации.
3. Описание алгоритма работы блога с авторизированным пользователем и неавторизированным

**Comment by romandr154** [comment]
Функционал блога в рамках бюджета. Учитывая ТЗ и дедлайн предлагаю оставить разработку блога в текущей редакции.
